# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP1/dataout_buf_IP1.xci
# IP: The module: 'dataout_buf_IP1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP1/dataout_buf_IP1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataout_buf_IP1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP1/dataout_buf_IP1.xci
# IP: The module: 'dataout_buf_IP1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP1/dataout_buf_IP1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataout_buf_IP1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
