set_property SRC_FILE_INFO {cfile:{C:/Users/DELL/Desktop/NoC on FPGA/design/XDC.xdc} rfile:../../../design/XDC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports sys_clk_p]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {RST}]
