# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/DELL/Desktop/NoC on FPGA/design/XDC.xdc

# IP: ip/datain_buf_IP/datain_buf_IP.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datain_buf_IP || ORIG_REF_NAME==datain_buf_IP} -quiet] -quiet

# IP: ip/dataout_buf_IP15/dataout_buf_IP15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dataout_buf_IP15 || ORIG_REF_NAME==dataout_buf_IP15} -quiet] -quiet
