# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/DELL/Desktop/NoC on FPGA/NoC.cache/wt} [current_project]
set_property parent.project_path {C:/Users/DELL/Desktop/NoC on FPGA/NoC.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/DELL/Desktop/NoC on FPGA/NoC.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_0.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_1.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_2.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_3.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_4.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_5.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_6.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_7.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_8.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_9.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_10.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_11.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_12.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_13.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_14.coe}}
add_files {{C:/Users/DELL/Desktop/NoC on FPGA/dat/data_in_15.coe}}
read_verilog -library xil_defaultlib {
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Control.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Crossbar.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/InputBuffer.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Network.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node0.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node1.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node10.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node11.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node12.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node13.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node14.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node15.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node2.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node3.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node4.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node5.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node6.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node7.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node8.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Node/Node9.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement0.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement1.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement10.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement11.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement12.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement13.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement14.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement15.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement2.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement3.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement4.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement5.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement6.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement7.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement8.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/ProcessorElement/ProcessorElement9.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/RouteCompute.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/Router.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/SwitchAlloc.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/VCAlloc.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/datain_buf.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/datain_buf_0.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_0.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_1.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_10.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_11.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_12.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_13.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_14.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_15.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_2.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_3.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_4.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_5.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_6.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_7.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_8.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/dataout_buf/dataout_buf_9.v}
  {C:/Users/DELL/Desktop/NoC on FPGA/design/NetworkOnFpga.v}
}
read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/datain_buf_IP/datain_buf_IP.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/datain_buf_IP/datain_buf_IP_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP15/dataout_buf_IP15.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP15/dataout_buf_IP15_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP1/dataout_buf_IP1.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP1/dataout_buf_IP1_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP2/dataout_buf_IP2.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP2/dataout_buf_IP2_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP3/dataout_buf_IP3.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP3/dataout_buf_IP3_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP4/dataout_buf_IP4.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP4/dataout_buf_IP4_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP5/dataout_buf_IP5.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP5/dataout_buf_IP5_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP6/dataout_buf_IP6.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP6/dataout_buf_IP6_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP8/dataout_buf_IP8.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP8/dataout_buf_IP8_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP9/dataout_buf_IP9.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP9/dataout_buf_IP9_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP10/dataout_buf_IP10.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP10/dataout_buf_IP10_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP11/dataout_buf_IP11.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP11/dataout_buf_IP11_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP12/dataout_buf_IP12.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP12/dataout_buf_IP12_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP13/dataout_buf_IP13.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP13/dataout_buf_IP13_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP14/dataout_buf_IP14.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP14/dataout_buf_IP14_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP7/dataout_buf_IP7.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP7/dataout_buf_IP7_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP0/dataout_buf_IP0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/dataout_buf_IP0/dataout_buf_IP0_ooc.xdc}}]

read_ip -quiet {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/ila_0/ila_0.xci}}
set_property used_in_synthesis false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc}}]

read_ip -quiet {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/NoC on FPGA/NoC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/DELL/Desktop/NoC on FPGA/design/XDC.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/DELL/Desktop/NoC on FPGA/design/XDC.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Network_FPGA -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Network_FPGA.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Network_FPGA_utilization_synth.rpt -pb Network_FPGA_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
